### ISSUE TITLE
How to: Play C&C Generals Zero Hour on Xevnet

### ISSUE THREAD

**Issue by Xevrac** [Xevrac/docs#6]
- Draft a guide on how a new player can install, configure and play our ZH matches
- GenZH and it's version
- GenTool
- ZeroTier
- etc.

**Comment by MrAmphib** [comment]
[How to - CNC ZH.docx](https://github.com/Xevrac/docs/files/10473590/How.to.-.CNC.ZH.docx)

**Comment by MrAmphib** [comment]
[How to - CNC ZH.docx](https://github.com/Xevrac/docs/files/10473606/How.to.-.CNC.ZH.docx)

**Comment by Xevrac** [comment]
> [How to - CNC ZH.docx](https://github.com/Xevrac/docs/files/10473606/How.to.-.CNC.ZH.docx)

cdd565437f1a6098ef9bebc3eba73a682c121793 This has been added - closing as completed
